In [1]:
import numpy as np
import array as arr

# Question 1.1 sol:

In [3]:
# Creating my own vander matrix
# Column stack stacks the arrays after taking the transpose of the 1-D array

def myvander(arr,N,increasing):
    if increasing == False:
        output = np.column_stack([arr**(N-1-i) for i in range(N)])
    if increasing == True:
        output = np.column_stack([arr**(i) for i in range(N)])
    print(output)

In [4]:
myvander(np.array([5,4,2,1]),3,False)

[[25  5  1]
 [16  4  1]
 [ 4  2  1]
 [ 1  1  1]]


In [5]:
myvander(np.array([5,4,2,1]),3,True)

[[ 1  5 25]
 [ 1  4 16]
 [ 1  2  4]
 [ 1  1  1]]


# Question 1.2 sol:

In [25]:
# Moving window question
# n = number of elements to be given as input

my_list = []
def my_window(n):
    for i in range(n):
        num = float(input(f"Enter the element number {i+1}: "))
        my_list.append(num)
        
    my_arr = arr.array('f',my_list)
    print(my_arr)
    
    #Size of window is taken as input
    window = int(input("Enter the window size: "))
    
    for i in range(n-window+1):
        sum = 0
        for j in range(i,i+window):
            sum += my_arr[j]
        avg = sum/window
        print(f"y{i+1} = {avg}")

In [26]:
my_window(10)

Enter the element number 1: 10
Enter the element number 2: 20
Enter the element number 3: 30
Enter the element number 4: 40
Enter the element number 5: 50
Enter the element number 6: 60
Enter the element number 7: 70
Enter the element number 8: 80
Enter the element number 9: 90
Enter the element number 10: 100
array('f', [10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0])
Enter the window size: 4
y1 = 25.0
y2 = 35.0
y3 = 45.0
y4 = 55.0
y5 = 65.0
y6 = 75.0
y7 = 85.0


In [27]:
my_window(13)

Enter the element number 1: 3
Enter the element number 2: 5
Enter the element number 3: 7
Enter the element number 4: 2
Enter the element number 5: 8
Enter the element number 6: 10
Enter the element number 7: 11
Enter the element number 8: 65
Enter the element number 9: 72
Enter the element number 10: 81
Enter the element number 11: 99
Enter the element number 12: 100
Enter the element number 13: 150
array('f', [10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0, 3.0, 5.0, 7.0, 2.0, 8.0, 10.0, 11.0, 65.0, 72.0, 81.0, 99.0, 100.0, 150.0])
Enter the window size: 3
y1 = 20.0
y2 = 30.0
y3 = 40.0
y4 = 50.0
y5 = 60.0
y6 = 70.0
y7 = 80.0
y8 = 90.0
y9 = 64.33333333333333
y10 = 36.0
y11 = 5.0
